name: 'CA: Photography'
favicon: null
layout_spectrum: 0.0619096530135721
typography_spectrum: 0.270819419529289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5830048471689224
  lightness: 0.09844715078361332
  saturation: 0.8552273057866842
  rhythmicContrast: 0.546727552311495
purpose: []
